name: Deploy Frontend application to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_SERVER }} << 'EOF'
            # Go to project folder
            cd /var/www

            # Remove old code completely
            rm -rf misoulmate

            # Clone fresh repo
            git clone -b main https://github.com/salvatoluice/misoulmate.git misoulmate

            # Move into the project
            cd misoulmate

            # Install dependencies and build
            npm install --production
            npm run build

            # Reload Nginx
            sudo systemctl reload nginx
          EOF
